filter:
  paths: [src/*]

checks:
  php:
    remove_extra_empty_lines: true
    remove_php_closing_tag: true
    remove_trailing_whitespace: true
    fix_use_statements:
      remove_unused: true
      preserve_multiple: false
      preserve_blanklines: true
    fix_php_opening_tag: true
    fix_linefeed: true
    fix_line_ending: true
    fix_doc_comments: true

tools:
  php_sim: true
  php_pdepend: true
  php_analyzer: true
  php_mess_detector: true
  external_code_coverage:
    timeout: '600'
